### PR TITLE
Fix BaseTool merge configurations

### LINKED ISSUE #738: Default tool configuration is overwritten by custom configuration passed to constructor
I think we should merge default and custom configuration objects.
See: https://github.com/cornerstonejs/cornerstoneTools/blob/vNext/src/tools/ReferenceLinesTool.js#L31

### PR DESCRIPTION
**Pull request by galelis**
# Changes
- Move merge into `baseTool.js`
- Fix `BaseBrushTool.js` after changes on `BaseTool.js`
- Add some unit tests for BaseTools and deepmerge

- Update all tools to start using this approach

(Closes #738)

### CODE REVIEW

File: src/tools/base/BaseTool.js [hunk 1]
```diff
@@ -1,4 +1,5 @@
 import mixins from './../../mixins/index.js';
+import lodash from 'lodash';
```
Comment (dannyrb) [inline src/tools/base/BaseTool.js]: Is there any way we can depend on _only_ `lodash`'s `merge` method instead of all of `lodash`?

Comment (dannyrb) [reply src/tools/base/BaseTool.js]: Bonus points if we can pull in just this utility method's source to reduce the number of external dependencies we have.

File: src/tools/annotation/ArrowAnnotateTool.js [hunk 2]
```diff
@@ -27,8 +27,8 @@ import { textBoxWidth } from './../../drawing/drawTextBox.js';
  * @extends Tools.Base.BaseAnnotationTool
  */
 export default class ArrowAnnotateTool extends BaseAnnotationTool {
-  constructor(configuration = {}) {
-    const defaultConfig = {
+  constructor(props = {}) {
+    const defaultProps = {
```
Comment (dannyrb) [inline src/tools/annotation/ArrowAnnotateTool.js]: This naming is better, but we may want to use something a bit more verbose to reduce confusion. I'll noodle on it.

File: src/tools/base/BaseBrushTool.js [hunk 3]
```diff
@@ -14,22 +14,8 @@ const { state, setters } = store.modules.brush;
...
-    super({
-      name,
-      strategies,
-      defaultStrategy,
-      configuration,
-      supportedInteractionTypes,
-      mixins,
-    });
+  constructor(...args) {
+    super(...args);
```
Comment (dannyrb) [inline src/tools/base/BaseBrushTool.js]: You added these lines here, but not to `BaseAnnotationTool`?

File: src/tools/base/BaseTool.js [hunk 4]
```diff
@@ -17,20 +18,28 @@ import mixins from './../../mixins/index.js';
...
+    props = lodash.merge({}, defaultProps, props);
+
+    const {
+      name,
+      strategies,
+      defaultStrategy,
+      configuration,
+      supportedInteractionTypes,
+      mixins,
+    } = props;
```
Comment (dannyrb) [inline src/tools/base/BaseTool.js]: I'm having a hard time remembering. Does this set the object's properties because the variables were instantiated here? Or do we need explicitly use `this.`? For clarity's sake, we may want to use `this`

File: src/tools/base/BaseTool.js (hunk 1 above)
Comment (galelis) [reply src/tools/base/BaseTool.js]: Good point indeed! But I thought about that too. 

We have lodash to perform a merge function for webpack config. 
We could easily change from the whole lodash to only cloneDeep, merge and mergeWith. 
But some of our npm packages also uses the whole lodash module, so dividing it to lodash.clonedeep/merge/mergewith will actually increase the size of our package.. at least the map increased in my tests.

File: src/tools/annotation/ArrowAnnotateTool.js (hunk 2 above)
Comment (galelis) [reply src/tools/annotation/ArrowAnnotateTool.js]: I will be happy to find out a better name :)

File: src/tools/base/BaseBrushTool.js (hunk 3 above)
Comment (galelis) [reply src/tools/base/BaseBrushTool.js]: So, I can add it there too.. but as we were not doing anything else in the constructor off `BaseAnnotationTool`, it may be useless.

File: src/tools/base/BaseTool.js (hunk 4 above)
Comment (galelis) [reply src/tools/base/BaseTool.js]: It does not. and also we do it one by one because we do some checks, as: 
- if we don't have any `defaultStrategy` we set the first. 
- if we don't have `strategies` we set as an empty array
...

File: src/tools/base/BaseTool.test.js [hunk 5]
```diff
@@ -16,31 +16,118 @@ jest.mock('./../../import.js', () => ({
 }));
 
 describe('BaseTool.js', () => {
-  describe('default values', () => {
-    it('has a default mode of "disabled"', () => {
+  describe('constructor()', () => {
+    it('should be instantiate with default mode of "disabled"', () => {
```
Comment (JamesAPetts) [inline src/tools/base/BaseTool.test.js]: `instantiate` -> `instantiated`

File: package.json [hunk 6]
```diff
@@ -56,13 +56,14 @@
     "gitbook-plugin-sitemap": "1.2.0",
     "jest": "23.4.0",
     "jest-junit": "5.1.0",
-    "lodash": "4.17.10",
+    "lodash.merge": "^4.6.1",
```
Comment (dannyrb) [inline package.json]: We've marked this as a `devDependency`, but because we `import` it into `BaseTool.js`, it should be under `dependencies`

**Comment by dannyrb** [comment]
You're my hero, @galelis! How do you feel about `deepMerge`?
If you resolve the one conflict, I would be more than happy to pull the `merge` lever.

**Comment by galelis** [comment]
> You're my hero, @galelis! How do you feel about `deepMerge`?
> If you resolve the one conflict, I would be more than happy to pull the `merge` lever.

I am happy with it. It is doing the merge as I was expecting. 
I tested on my OHIF, worked well with bidirectional and arrowAnnotate

I will fix the conflict and change all other tools to use it.

File: src/tools/base/BaseTool.js (hunk 1 above)
Comment (galelis) [reply src/tools/base/BaseTool.js]: Fixed this issue.

File: src/tools/base/BaseBrushTool.js (hunk 3 above)
Comment (galelis) [reply src/tools/base/BaseBrushTool.js]: I came back with the constructor.

File: src/tools/base/BaseTool.test.js (hunk 5 above)
Comment (galelis) [reply src/tools/base/BaseTool.test.js]: I fixed the typo

File: package.json (hunk 6 above)
Comment (galelis) [reply package.json]: I have removed both dependencies.

File: src/tools/base/BaseTool.js [hunk 7]
```diff
@@ -1,4 +1,5 @@
 import mixins from './../../mixins/index.js';
+import merge from 'lodash.merge';
```
[the remark this answers is not in the document]
Comment (galelis) [reply src/tools/base/BaseTool.js]: I agree with you Danny, thanks for you insights. 
I have moved the merge function into a base js file into our code, avoiding the use of a npm module only for that.

**Comment by galelis** [comment]
Hey @dannyrb,
I have fixed the conflicts, and change all remaining tools.

**Comment by dannyrb** [comment]
@galelis, I realize this is waiting on me. I have 👀 on it. Sorry for the delay.

File: package.json [hunk 8]
```diff
@@ -75,8 +74,8 @@
   },
   "dependencies": {
     "@babel/runtime": "7.1.2",
-    "cornerstone-math": "0.1.7",
-    "debug": "4.1.1"
+    "debug": "4.1.1",
+    "cornerstone-math": "^0.1.7"
```
Comment (dannyrb) [inline package.json]: Can we switch this back to an exact version?

**Comment by dannyrb** [comment]
Does this account for the new CircleTool?

**Comment by dannyrb** [comment]
@galelis, this looks how I remember it. AFAIK, this doesn't break anything (if we've accounted for the circle tool). We can merge, and address any breaks in a patch. This should get us to the expected behavior ^_^

Thanks for all of your work on this.

**Comment by galelis** [comment]
@dannyrb Just updated the CircleRoi with latest changes to get props merged as the others :) 

@evren217 and Danny, seems that its working, have you guys checked? 



NOTEs: Crosshair and DoubleTapToFit is not working (I think) but its also not working on other netlify instances, I can chack and fix in another PR)

**Comment by dannyrb** [comment]
DoubleTapToFit works for me on my phone. I'm going to merge this. I'll try to be extra responsive this next week to any issues that may have been caused by this with patch updates -- hopefully we're in the clear ^_^
